### ISSUE TITLE
Check the cuts for misID sample

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#100]
Claim: All we need to do for misID sample are:

- Use a different stripping line
- Remove the `Mu` PID cuts at DaVinci level

Both are already implemented in our DaVinci script.

I have a very good reason in believe my claim is true: Phoebe only has two scripts, one for `D*` and one for `D0`. I don't see any keyword starting with `fake`, so there's should be NO difference in the offline cut department, and we already know the differences in DaVinci part.

@afernez nonetheless, can you confirm my claim? You just need to briefly check the code, and if everything's well, maybe ask Phoebe directly, just to be sure.

FYI @manuelfs

**Comment by yipengsun** [comment]
@afernez I can't find the `fakemu` line in the committed DaVinci scripts either.

However, from one of the earliest tags of THIS project, I was able to locate Phoebe's DV script at the time:
https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/0.1/2012-b2D0MuXB2DMuNuForTauMuLine/ntuple_options-sample.py

This does contain prescription about the fake line. Maybe you can start from here?

**Comment by afernez** [comment]
I messaged Phoebe, and she said there weren't any updates to the DaVinci scripts, so that one you linked to in the most recent comment should be correct to reference for what changes when producing the misID sample. Compared to data, the misID sample just uses a different stripping line (with "fake" keyword)- and actually, the missing muPID cut is included in this different stripping line. It seems like you repeat the stripping line muPID cut in your DaVinci script [here](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/b93f8afaa34bf94821cf69f08518c7058e8ace36/run2-rdx/reco_Dst_D0.py#L314), but still the way you handle it currently (skipping it for misID) is correct.

Since this confirms your claim above, I'll close this issue.
