### ISSUE TITLE
fix logic for setting minimum mDD for dalitz corrections

### ISSUE THREAD

**Issue by CoffeeIntoScience** [umd-lhcb/lhcb-ntuples-gen#123]
Currently committed `master` sets the wrong minimum for mDD. For the D0 sample it should be m_D+m_D (~1864.whatever *2), for the Dst sample it should be m_Dst+m_D (~2010+1864.whatever). The minimum is *not* set by parent, it is set by sample.

https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/b150b044dc770f50f7bd6ff7ca8dac3696eb5a71/include/functor/rdx/cut.h#L311-L316

I had thought this was fixed as per an earlier discussion, and maybe it's just fixed in some local somewhere, but if not it needs to be fixed and the change needs to be propagated to the histograms.

**Comment by yipengsun** [comment]
Looking at my `mDD`:
![mdd_us](https://user-images.githubusercontent.com/33738176/222864059-28a11542-03e0-424b-baa7-65f9aea957dd.png)

where I'm looking at the **TRUE** invariant mass of the $DD_{other}$ pair, and some of them are below `3800` probably due to mis-reconstructions.

Phoebe's `mDD`:
![image](https://user-images.githubusercontent.com/33738176/222864140-bd308ee8-e7f1-4bf8-9922-e5418aafe150.png)

I think this is **SOMEHOW** the invariant mass of the reco'ed? Because it looks like a continuous spectrum. I'd like to confirm that we **SHOULD** be using the **TRUE** quantities for Dalitz-inspired variations, right?

**Comment by yipengsun** [comment]
Edited the post above to make sure we are looking at the same range, and forget about my comment on the **TRUE** vs **RECO**, because both should be **TRUE**! The invariant mass of the pair is OF COURSE going to be a continuous spectrum!
