### ISSUE TITLE
Steps towards 2nd stage ntuples

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/lhcb-ntuples-gen#13]
- [x] Comparison with Phoebe's ntuples
- [x] Get MC signal and normalization `.DST` files
- [x] Script to read branch names from input ntuples, and output simplified names with no capitals (eg `Dst_2010_minus_ENDVERTEX_X -> ds_vtx_x`)
- [x] Generator of 2nd stage ntuple with some branches just copied and others calculated. Input text files indicating branches to be copied and names, and full list of final branches and types.

**Comment by yipengsun** [comment]
We need to have the following functionality:
* Parse `drop, keep` command from a file, with regular expression support.
  Since we are using `gcc 6.2`, the `regex` should be in the standard library. See [1] for details.
* Skimming: Drop unused branches as a whole
* Slimming: Drop events (based on what?)
* Rename branches

[1]: https://en.cppreference.com/w/cpp/regex

**Comment by yipengsun** [comment]
It is worth noting that `gcc 6.2.0` supports `c++ 14`: [1]. So we can use the latest standardize `c++`.


[1]: https://gcc.gnu.org/projects/cxx-status.html

**Comment by yipengsun** [comment]
The MC `.DST` files are listed in the [wiki entry](https://github.com/umd-lhcb/lhcb-ntuples-gen/wiki/lhcb-ana-2014-052-v2r1).

**Comment by yipengsun** [comment]
The new baby maker, with the basic ability to keep/drop certain branches and rename branches are in `newbaby` branch.

Later today I'll add selection functionality, as well as running arbitrary calculations. 

Note that I decided to use `Python` to generate `C++` code, instead of `C++` to generate `C++`.

**Comment by yipengsun** [comment]
Now the `newbaby` branch should have feature parity with @manuelfs's original `babymaker`. 

I claim that my implementation is more elegant and is more automatized.

**Comment by yipengsun** [comment]
I've generated Run 1 MC ntuples in:
```
/2012-b2D0MuXB2DMuNuForTauMuLine/data/sample/BCands_Dst-mc-py6-sim08a-mag_down-subset.root
```

@bflaggs Please validate this with Phobe's.

**Comment by yipengsun** [comment]
@manuelfs Please note that currently I'm not using Phoebe's modified version of `MCTupleToolHierarchy`. This shouldn't matter much currently. 

I'll migrate to that as part of migration to `DaVinci-v45` process.

**Comment by yipengsun** [comment]
We've finished our comparison, and saw some discrepancies. The resolution of these problems will be tracked separately.
