### ISSUE TITLE
Reconstructing run 2 sample MC locally

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#58]
I should see if our upcoming run 2 MC samples reconstruct "without surprise". I'll work on this on branch `run2-mc-validation` branch.

**Comment by yipengsun** [comment]
The Production ID for the large FullSim requests are: `74234, 74233` though I don't see LFNs in the production's **view** window.

**Comment by yipengsun** [comment]
Anyway, I'll start with:
- `B0 -> D*- mu nu`: `/MC/2016/11574021/Beam6500GeV-2016-MagDown-Nu1.6-25ns-Pythia8/Sim09j/Trig0x6139160F/Reco16/Turbo03a/Filtered/D0TAUNU.SAFESTRIPTRIG.DST`
- `B+ -> D*0 mu nu`: Same LFN, with event type `12773410` substituted

**Comment by yipengsun** [comment]
This MC request twiki might be useful:
https://twiki.cern.ch/twiki/bin/view/LHCb/DownloadAndBuild#1_Get_the_productions_ID_number

**Comment by yipengsun** [comment]
@manuelfs @afernez I've merged the `run2-mc-validation` to `master`. And here's the statistics with my local run for run 2 normalization MC (`B -> D* mu nu`):

| Type | # of events/candidates |
|---|---|
| Event in DST | 41879 |
| tuple: `B -> D0 mu nu` | 35063 |
| tuple: `B -> D* mu nu` | 22985 |
| tuple: MC `B -> D0 mu nu` | 18 |
| tuple: MC `B -> D* mu nu` | 31433 |

Related files:

- [`DaVinci` log](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/2d46724db33bcbf0a213d608110d83d13632a919/run2-rdx/logs/Dst_D0-21_01_26-mc.log)
- [sample ntupe](https://github.com/umd-lhcb/lhcb-ntuples-gen/blob/2d46724db33bcbf0a213d608110d83d13632a919/run2-rdx/samples/Dst_D0--21_01_26--mc--Bd2DstMuNu--2016--md--py8-sim09j-dv45-subset.root)

The latter one can be obtained with `git annex get` after synchronizing.

**Comment by yipengsun** [comment]
Taking a look at similar statistic with run 1 MC (with `B -> Dst tau nu`):

| Type | # of events/candidates |
|---|---|
| Event in DST | 27970 |
| tuple: `B -> D0 mu nu` | 7019 |
| tuple: `B -> D* mu nu` | 4790 |
| tuple: MC `B -> D0 mu nu` | 14 |
| tuple: MC `B -> D* mu nu` | 17 |
| tuple: MC `B -> D* tau nu` | 27971 |

**Comment by yipengsun** [comment]
Note that in run 2, the number of correct MC decay tree ntuple (31433) is smaller than the number of raw events. This is a HUGE red flag as we had something similar in run 1: https://github.com/umd-lhcb/lhcb-ntuples-gen/issues/51#issuecomment-708517957

This discrepancy was due to NOT taking `B0` oscillation into account in the `B0 -> Dst mu nu` decays (the `tau nu` decay was handled). I've fixed this in both run's scripts and fixed the table.

**Comment by afernez** [comment]
I'll write this comment here since this is where Yipeng posted the stats for his productions. I did a local test production with run 1 2012 sim08e (so not RICHless) normalization (B -> D\* mu nu), and the efficiency indeed turned out to be more reasonable, in contrast to the RICHless sim09a production that retained ~1% of events using our run 1 reco script. Here are the statistics:

| Location | Events/Candidates |
|---|---|
| Events in DSTs/on disk | 48850 |
| tuple: `B -> D0 mu nu` | 13275 |
| tuple: `B -> D* mu nu` | 9350 |
| tuple: MC `B -> D0 mu nu` | 26 |
| tuple: MC `B -> D* mu nu` | 48881 |
| tuple: MC `B -> D* tau nu` | 1 |

As I'll note in #55, I'll start a full production for sim08e now and use this to compare to Phoebe's run 1 and our run 2 FullSim ntuples.
I'll commit the log file and output ntuple from the local test production like Yipeng did above, too.

**Comment by yipengsun** [comment]
We've reconstructed run2 FullSim locally. For tracker-only, refer to #59.
